{% set name = "dbt-state" %}
{% set version = "2.45.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: cc97fb46ab987a704914fcc5fae968a2ac52c11fe80c2f85d0942bb817a90a65
  patches:
    - patches/0001-fix-pyproject-file.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - dbt-state = dbt_state.cli.main:cli
  # No dbt-core for Python 3.13+
  skip: true  # [py<39 or py>313]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - aenum
    - authlib
    - click >=8.0.0
    - dacite
    - dbt-core >=1.6.0
    - grpcio >=1.60.0
    - requests
    - humanize
    - protobuf>=4.0.0
    - pytimeparse2
    - query-cache-protobuf
    - query-cache-common
    - rich
    - pyyaml
    - sqlglot >=27.6.1
    - typing_extensions >=4.6.0

test:
  imports:
    - dbt_state
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.getdbt.com/product/dbt-state
  summary: dbt enables data analysts and engineers to transform their data using the same practices that software engineers use to build applications.
  license: Apache-2.0
  license_family: Apache
  license_file: PKG-INFO
  description: |
    dbt enables data analysts and engineers to transform their data using the same practices that software engineers use to build applications.
  doc_url: https://pypi.org/project/dbt-state
  dev_url: https://pypi.org/project/dbt-state

extra:
  recipe-maintainers:
    - Andrii-Osipov